config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'blogs#index'
  resources :blogs
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index
  
  def index
    @blogs = Blog.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(text: blog_params[:text], user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

  def edit
    @blog = Blog.find(params[:id])
  end
 
  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  private
  def blog_params
    params.permit(:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @blogs = current_user.blogs.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
    <div class="content_post">
      <% if user_signed_in? && current_user.id == blog.user_id %>
        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
          <ul class="more_list">
            <li>
              <%= link_to 'EDIT', "/blogs/#{blog.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to 'DELETE', "/blogs/#{blog.id}", method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
        <%= simple_format(blog.text) %>
    </div>

app/views/blogs/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        POST COMPLETED
      </h3>
      <a class="btn" href="/blogs">BACK TO HOME</a>
    </div>
  </div>

app/views/blogs/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        DELETION COMPLETED
      </h3>
      <a class="btn" href="/">BACK TO HOME</a>
    </div>
</div>

app/views/blogs/edit.html.erb
  <div class="contents row">
    <%= form_for(@blog, url: blog_path(@blog)) do |f| %>
      <h3>
        DO EDIT
      </h3>
      <textarea cols="30" name="text" placeholder="text" rows="10"><%= @blog.text %></textarea>
      <input type="submit" value="SENT">
    <% end %>
  </div>

app/views/blogs/index.html.erb
<div class="contents row">
  <% @blogs.each do |blog| %>
    <%= render partial: "blog", locals: { blog: blog } %>
  <% end %>
  <%= paginate(@blogs) %>
</div>

app/views/blogs/new.html.erb
<div class="contents row">
  <%= form_for @blog do |f|%>
    <h3>
      POST
    </h3>
    <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
    <input type="submit" value="SENT">
  <% end %>
</div>

app/views/blogs/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        EDIT COMPLETED
      </h3>
      <a class="btn" href="/">BACK TO HOME</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ntb-BLOG</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">ntb-BLOG</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete %>
          <a class="post" href="/blogs/new">POST</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "SIGN IN", new_user_session_path, class: 'post' %>
          <%= link_to "SIGN UP", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
    </div>
  </header>

    <%= yield %>

    <footer>
      <p>
        Copyright ntb-BLOG 2019.
      </p>
    </footer>
  </body>
</html>